### ISSUE TITLE
feat: fail to apply the promise if there are duplicated container names within a workflow

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#114]
A promise cannot contain workflows with duplicated container names, like in the example below:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jenkins
spec:
  api: # crd
  # any other fields
  workflows:
    resource: # or promise:
      configure: # or delete
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: pipeline-1
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/a-configure-pipeline:v0.1.0
            name: configure-pipeline # <<<< duplicated
          - image: ghcr.io/syntasso/kratix-marketplace/b-configure-pipeline:v0.1.0
            name: configure-pipeline # <<<< duplicated
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: pipeline-2
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/b-configure-pipeline:v0.1.0
            name: configure-pipeline
```

However, when the user applies this promise, they receive no immediate feedback.

A better experience would be to fail the apply, and output a message with the reason for the error.

**Comment by ChunyiLyu** [comment]
Can confirm this is still an issue
```
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: test
spec:
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: test
          spec:
            containers:
              - image: busybox
                name: configure-pipeline
              - image: busybox
                name: configure-pipeline
                ```
