### ISSUE TITLE
Feat: As Penny I want full control over where files are scheduled in a Destination

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix#129]
Follow up from https://github.com/syntasso/kratix/issues/127

# Background

As part of https://github.com/syntasso/kratix/issues/127 you can now specify that files written to the destination either:
- follow our existing convention of nested directories, e.g. `kratix/platform-cluster/resources/default/redis/example/instance-configure/5058f/redis-instance.yaml`
- are placed at the top level directory

These are 2 common use cases we think we will run into, but is not the definitive list. To enable users with more complex use cases we want to support expressing your own desired filepath structure via a key. 

## Proposal
Expand the `filepathExpressionType` key to have an additional value `custom` and introduce a new `filepathExpression` value. e.g.:

```
spec:
  filepathExpression:
    type: custom                
    resource: "resources/$namespace/$promise_name-$resource_name-$pipeline_name-$workload_group-$filename"
    promise:  "promises/$promise_name-$filename"
```

We should expose all the variables we use today to template our default to the user:
for resources:
- filename
- promise name
- resource name
- workload group
- namespace
- pipeline name

for promises:
- filename
- promise name
- workload group
- pipeline name

### Templating style

TBD what format the templating should take, in the example its bash variables. We could do something like the go-templating that helm uses `{{ .PromiseName }}`. Investigate which makes sense and use that

**Comment by tdiaque** [comment]
Hello,
Has the use of **filepath.mode = none** been released yet? I see we can configure that now per the docs but I am receiving the following error upon attempting to apply my destinations.yaml
**The Destination "flux-hub" is invalid: spec.filepath.mode: Invalid value: "string": filepath.mode is immutable**

```
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: flux-hub
  labels:
    environment: platform
spec:
  filepath:
    mode: none
  stateStoreRef:
    name: plat-eng-gitops-git
    kind: GitStateStore
```

I am attempting to create a promise to onboard tenants onto our FluxCD Hub/Spoke and I figured this might allow me to push the files to the specific directory structure that FluxCD is expecting.
