### ISSUE TITLE
feat: allow promise writers to define the permissions for the pipeline service account

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#197]
Currently, users need to out-of-bands manage any Role/RoleBindings (or the cluster equivalent) for the Service Account their pipelines run. We want to bring that into the Promise, in such a way that the Promise writer can define the cluster permissions their pipelines need.

To achieve that, we will introduce a new field in the Pipeline spec.

It should look something like this:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-name
spec:
  rbac:
    serviceAccount: my-sa # optional

    permissions:
    - apiGroups: [""]
      resources: ["secrets"]
      resourcesNames: ["git-creds"]
      verbs:  ["get"]
    - apiGroups: [""]
      resources: ["configmap"]
      verbs:  ["*"]

  containers:
  - name: hello
    image: myorg/myimage
```

The above spec should result in the following being created:

- One Kubernetes Role, containing the rules defined above.
- One Kubernetes RoleBinding, attaching the role to the SA.

> [!NOTE]
> Updating the pipeline `rbac.permissions` should update the existing role; Deleting the Promise should delete the Role and RoleBinding

## Tasks
- [x] Introduce the new `rbac.permissions` field
- [x] Create the Role/RoleBinding according to the provided values
- [x] Delete
- [ ] Update docs
