### ISSUE TITLE
[feat] Kratix should warn when a Promise RBAC specifies a namespaced permissions for a cluster-wide resource

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix#214]
If a resource is cluster wide, e.g. `Namespaces`, you must ensure that you use a `ClusterRole` instead of a `Role` to give permissions to it. In the `rbac.permissions` feature this is done by setting `resourceNamespace: "*"`, which could easily be forgotten.

Example:
```
            rbac:
              permissions:
              - apiGroups:
                  - platform.kratix.io
                resources:
                  - destinations
                verbs:
                  - list
```

this will create a `Role`/`RoleBinding`, however the `Role` will be useless, since it refererences a cluster-wide resource that isn't namespaced. We should emit a warning/error on validating webhook when this happens, and suggest that they change it to:

```
            rbac:
              permissions:
              - apiGroups:
                  - platform.kratix.io
                resources:
                  - destinations
                verbs:
                  - list
                resourceNamespace: "*"
```
