### ISSUE TITLE
bug: setting `path` on GitStateStore leads to output files being "written" as directories in the state store

### ISSUE THREAD

**Issue by jbsf2** [syntasso/kratix#218]
Hi, in at least some circumstances, setting the `path` on GitStateStore can lead to output files being unexpectedly written to the state store as directories, rather than as files.

We have a promise whose workflow produces two output file:

```
./output/mo-test-namespace.yaml
./output/canary-configmap.yaml
```

A resource request supported by this promise is meant to be scheduled to a destination that has a GitStateStore. The  yaml for the GitStateStore looks something like this:

```
apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: jupiter-git-statestore
  namespace: kratix-platform-system
spec:
  branch: main
  path: /
  authMethod: ssh
  secretRef:
    name: statestore-ssh-key
    namespace: kratix-platform-system
  url: (github url)
```

After the resource request is processed, what shows up in the state store is this: 

<img width="824" alt="Screenshot 2024-08-08 at 12 21 50 PM" src="https://github.com/user-attachments/assets/e39dc1b0-9239-46b7-86f3-9bdb0c816564">

Eventually I noticed in the docs that `path` is optional, and I removed it. Subsequently, resource requests wrote actual yaml files to the git state store, as one would expect, rather than directories.

Just to see what would happen, I then tried setting the path to "/foo". The unexpected behavior returned - the yaml files appear as directories rather than files:

<img width="1136" alt="Screenshot 2024-08-08 at 2 58 53 PM" src="https://github.com/user-attachments/assets/5736f22a-d551-4e74-82e2-58d674ad79e8">

Perhaps there are other factors also coming into play, though I have not narrowed them down. That said, I'd submit that having the output files show up as directories is undesired behavior under any circumstances :-)
