### ISSUE TITLE
Chore: Provide available condition on the Promise object

### ISSUE THREAD

**Issue by abangser** [syntasso/kratix#321]
Right now the conditions available on promise are:
```
  conditions:
  - lastTransitionTime: "2025-01-10T17:13:13Z"
    message: Pipelines completed
    reason: PipelinesExecutedSuccessfully
    status: "True"
    type: ConfigureWorkflowCompleted
  - lastTransitionTime: "2025-01-10T17:13:16Z"
    message: Requirements fulfilled
    reason: RequirementsInstalled
    status: "True"
    type: RequirementsFulfilled
```

While there is a status field (`status: Available`) this is not as handy to do a status check as we can't use `kubectl wait`.

Ideally we would set an availability condition at the same time that we set that status field.
