### ISSUE TITLE
feat: set resource request status and emit events when delete workflow fails

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix#356]
## Context

When delete workflow of a resource request fails, we don’t update the resource request status or publish any event. This makes it harder for users to know what’s going on:
```
❯ k delete testing kratix-test
testing.test.kratix.io "kratix-test" deleted
...
kratix-testing-kratix-test-resource-pipeline0-1f7f5-vc6j4      0/1     Error     1 (8s ago)   9s
❯ k describe testing kratix-test
Name:         kratix-test
API Version:  test.kratix.io/v1alpha1
Kind:         testing
Metadata:
  Deletion Timestamp:             2025-02-06T15:14:38Z
...
Spec:
...
Status:
  Observed Generation:  1
Events:   
```

We should update the Status of the resource request at least to notify users that delete workflow has failed and resource request is failing to be deleted. We should also emit an event.

Promise used to reproduce this:
```
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: testing
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: testing.test.kratix.io
    spec:
      group: test.kratix.io
      names:
        kind: testing
        plural: testing
        singular: testing
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
            type: object
        served: true
        storage: true
  workflows:
    resource:
      delete:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: resource-pipeline0
        spec:
          containers:
            - image: busybox
              name: fail
              command:
                - /bin/sh
              args:
                - -c
                - exit 1
```
