### ISSUE TITLE
feat: Make the canary resources optional

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix#423]
Today kratix writes the following canary resource to each destination, in this example `region-asia` Destination
```
kratix/region-asia/dependencies/kratix-canary-namespace.yaml
kratix/region-asia/dependencies/mongodb/5058f/static/mongodb-dependencies.yaml
```

Sometimes either:
- The end destination is not K8s
- The GitOps agent doens't have permissions to create the resoruces, e.g. Namespace
- The user doesn't want these things at all

We should provide the ability to disable the creation of these.

In the future we might want to make the content & name configurable, so we should think about what API fields we want to add now that might support that feature in the future, e.g.:
```
kind: Destination
spec:
  canaries:
    disabled: true/false
    # future could add:
    # dependencies:
      # content: "test dep file"
      # path: "CANARY-DEP.md"
    # resource:
      # content: "test resource file"
      # path: "CANAR-RES.md"
```
