### ISSUE TITLE
feat: Let users disable Kratix keeping the nested directory structure when scheduling to multi destinations

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix#441]
Scenario: Pipeline that schedules to two destination, e.g.:
```yaml
ls /kratix/output/

deployment.yaml
terraform/
  main.tf


cat /kratix/metadata/status.yaml
- matchLabels:
    env: dev
- directory: terraform
  matchLabels:
    env: terraform
```

This results in the following being written to the two destinations (assuming both have filepath mode=none)
```
ls statestore/
k8s-destination/
  deployment.yaml
terraform-destination/
  terraform/
    main.tf
```

What I really want is to be able to have:
```
ls statestore/
k8s-destination/
  deployment.yaml
terraform-destination/
  main.tf
```

## why?

This is because my terraform reconciler is set to read files *at the top level directory* of `terraform-destination`, it doesnt support scanning sub dirs.

I'm not blocked by this, as there are workarounds (extra pipelines), but its frustrating

## implementation idea

```yaml
cat /kratix/metadata/status.yaml
- matchLabels:
   env: dev
- directory: terraform
  inheritDirName: false # some better named field
  matchLabels:
    env: terraform
```
