### ISSUE TITLE
When Destination `Cleanup: none` is used, files in state stare are being cleaned up

### ISSUE THREAD

**Issue by Phiph** [syntasso/kratix#455]
Hey,

I've noticed some behaviour that's different to what's documented. 

The documentation for the [destination](https://docs.kratix.io/main/reference/destinations/intro) cleanup https://docs.kratix.io/main/reference/destinations/intro

```
  # Optional, defaults to `none`
  # The cleanup policy to use when deleting the Destination, valid options are:
  #   - none: No cleanup will be performed
  #   - all: All files in the State Store for this Destination will be deleted
  #          when the Destination is deleted
  cleanup: none
```

I'm setting up a git repo that's storing Terraform Files, and I want to manually configure the file deletion process. I've set the `cleanup: none` property, but i'm noticing that Kratix is deleting the state files.

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/4d869c25-a75a-4829-b8d6-62e78b423eda" />

My state config:

```
apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: terraform-ops
spec:
  branch: main 
  path: /
  # Valid options: basicAuth, and ssh; defaults to basicAuth
  authMethod: basicAuth 
  # Required
  secretRef:
    # The name and namespace of the secret to use to authenticate: required
    name: git-auth
    namespace: kernel
  url: https://github.com/phiph/kratix-terraform-ops.git
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: terraform-ops
  labels:
    environment: terraform-ops
spec:
  filepath:
    mode: nestedByMetadata
  cleanup: none
  path: /
  stateStoreRef:
    kind: GitStateStore
    name: terraform-ops
```
