### ISSUE TITLE
bug: BucketStateStoreReconciler panics when spec.secretRef not provided (IAM)

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix#461]
## Context

Given a bucketstatestore that looks like:
```
apiVersion: platform.kratix.io/v1alpha1
kind: BucketStateStore
metadata:
  name: default
spec:
  authMethod: IAM
  bucketName: kratix
  endpoint: blah
  insecure: true
#  secretRef: not provided because using IAM not accessKey
```

You get nil pointer panics in bucket state store reconcilier:
```
E0515 09:08:52.027744       1 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
	goroutine 120 [running]:
	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x218f700, 0x3509e60}, {0x1a96820, 0x3476300})
		/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:107 +0x98
	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x218f700, 0x3509e60}, {0x1a96820, 0x3476300}, {0x3509e60, 0x0, 0x40009e33a8?})
		/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:82 +0x60
	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40005fe1c0?})
		/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:59 +0x114
	panic({0x1a96820?, 0x3476300?})
		/usr/local/go/src/runtime/panic.go:791 +0x124
	github.com/syntasso/kratix/internal/controller.(*BucketStateStoreReconciler).SetupWithManager.func1({0x21ba4e8?, 0x4000159680?})
		/workspace/internal/controller/bucketstatestore_controller.go:91 +0x34
```

This is because we don't do any checks and always assume secretRef is present `return []string{secretRefIndexKey(stateStore.Spec.SecretRef.Name, stateStore.Spec.SecretRef.Namespace)}`

Fix it!
