### ISSUE TITLE
feat: support git state store ssh with user other than 'git'

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix#463]
## Context

Given a GitStateStore that uses ssh key as the authentication method:

```
kind: GitStateStore
apiVersion: platform.kratix.io/v1alpha1
metadata:
  name: github
spec:
  authMethod: ssh
  secretRef:
    name: github-credentials
    namespace: default
  url: a-user@xxx.ghe.com:xx/kratix-state-store.git
  branch: kratix
```
Our git writer always connect as user `git`: https://github.com/syntasso/kratix/blob/main/lib/writers/git.go#L54, which does not support connect as any other user.

Make the user configurable.
