### ISSUE TITLE
feat: make job backoff limit configurable in Kratix workflows

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#473]
## Context

By default, Kubernetes will retry 6 times to make the job pass, following an exponential backoff strategy. In case of failure, users might want to choose not to re run the workflow, or if they are actively debugging, they might want a higher `backoffLimit` so the workflow can be re run more than the current default, which is 6.

We could make this configurable both at the global level and at the Promise level. In this story, we will implement both.

## UX

In the Pipeline spec, users should be able to configure the backoffLimit:

```yaml
# promise.yaml
# ...
spec:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
        spec:
          jobOptions:
            backoffLimit: 3
          containers:
          - image: my-image
            name: my-container
```

In the Kratix Config, users should be able to configure the default backoffLimit:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratix
  namespace: kratix-platform-system
data:
  config: |
    workflows:
      jobOptions:
        defaultBackoffLimit: 4
```

## Scenarios

```gherkin
# Global Backoff Limit
Given I have a Kratix Config with `workflows.jobOptions.defaultBackoffLimit` set to X
When any workflow job is created
Then its `spec.backoffLimit` is set to X

# Backoff Limit set in the Workflow
Given I have a Workflow with `spec.jobOptions.backoffLimit` set to X
When the workflow job is created
Then its `spec.backoffLimit` is set to X

# Workflow backoffLimit has precedence
Given I have a Kratix Config with `workflows.jobOptions.defaultBackoffLimit` set to X
And I have a Workflow with `spec.jobOptions.backoffLimit` set to Y
When any workflow job is created
Then its `spec.backoffLimit` is set to Y
```
