### ISSUE TITLE
bug: when the Promise is invalid, installing it via Promise release gives you no feedback

### ISSUE THREAD

**Issue by kirederik** [syntasso/kratix#87]
### Steps to reproduce
1. Create an invalid promise
1. Add the following label to it: `kratix.io/promise-version: v1.0.0+beta.1`
2. Try to install this promise
3. See that it fails
4. Create a Promise Release pointing to this invalid promise
```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: PromiseRelease
metadata:
  name: promise
spec:
  version: v1.0.0+beta.1
  sourceRef:
    type: http
    url: <url>
```
5. Apply the Promise release

### Expected

Some feedback

### Actual

None
