### ISSUE TITLE
feat: Expose SSH configuration for GitStateStore

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix#88]
When using AWS CodeCommit as my git repository for my statestore I can only use the HTTPS basic auth method currently. To use  SSH I need to be able to make the following changes to the SSH config:
![Screenshot 2024-02-22 at 10 27 46](https://github.com/syntasso/kratix/assets/19669095/828b5a75-093d-4fde-9997-882e09e99fa0)

Ideally Kratix would expose setting this sort of configuration through either the `GitStateStore` kind or in the `Secret` that gets referenced. E.g.:

```
apiVersion: platform.kratix.io/v1alpha1
kind: GitStateStore
metadata:
  name: default
spec:
  authMethod: basicAuth
  branch: main
  secretRef:
    name: aws-git
    namespace: default
  url: https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/kratix-jake
  sshConfig: |
     Host git-codecommit.*.amazonaws.com
       User USER_ID
       IdentityFile ~/.ssh/codecommit_rsa
```

or 
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-git
  namespace: default
data:
  password: .....
  username: .....
  sshConfig: |
   Host git-codecommit.*.amazonaws.com
     User USER_ID
     IdentityFile ~/.ssh/codecommit_rsa
```

Docs: https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html?icmpid=docs_acc_console_connect_np
