### ISSUE TITLE
Feat: Provide support for multiple configure workflows

### ISSUE THREAD

**Issue by SaphMB** [syntasso/kratix#90]
At present, Promise writers can only write a single `configure` workflow for their Promise or Resource Request. The `workflows.configure`  key already takes a list of `Pipelines` to execute but at present, Kratix only selects the first one and executes it.

**Expectation: The Pipelines run in the order they are specified**

Given a Promise or Resource Request has the following specification:

```
workflows:
    resource/promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: configure-a
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/a-configure-pipeline:v0.1.0
            name: configure-a-pipeline
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: configure-b
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/b-configure-pipeline:v0.1.0
            name: configure-b-pipeline
```

When the Configure Workflow runs, the `configure-a` Pipeline will run and upon it's completion (as indicated by the status), the `configure-b` Pipeline will run.

**Expectation: The Pipelines infer completion from the Pipeline status**

Given the above Configure Workflow
When `configure-a` runs, `configure-b` will identify that it has completed via the Pipeline status
