### ISSUE TITLE
feat: fail to apply the promise if there are duplicated workflow names

### ISSUE THREAD

**Issue by SaphMB** [syntasso/kratix#91]
A promise cannot contain workflows with duplicated names, like in the example below:

```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jenkins
spec:
  # ...
  workflows:
    resource: # or promise:
      configure: # or delete
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: my-pipeline  # <<<< duplicated
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/a-configure-pipeline:v0.1.0
            name: configure-pipeline-1
          - image: ghcr.io/syntasso/kratix-marketplace/b-configure-pipeline:v0.1.0
            name: configure-pipeline-2
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: my-pipeline  # <<<< duplicated
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/b-configure-pipeline:v0.1.0
            name: configure-pipeline
```

That's because the pipeline name is used in the Work that's created by the pipeline.

However, when the user applies this promise, Kratix accepts it. The user will only find out the problem much later, and even so it will be a bit obscure for them to find out whats wrong.

A better experience would be to fail the apply, and output a message with the reason why.
